/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CarFinderRouteImport } from './routes/car-finder'
import { Route as FinancingRouteImport } from './routes/financing'
import { Route as TestDriveRouteImport } from './routes/test-drive'
import { Route as InventoryIndexRouteImport } from './routes/inventory.index'
import { Route as InventoryVehicleIdRouteImport } from './routes/inventory.$vehicleId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CarFinderRoute = CarFinderRouteImport.update({
  id: '/car-finder',
  path: '/car-finder',
  getParentRoute: () => rootRouteImport,
} as any)
const FinancingRoute = FinancingRouteImport.update({
  id: '/financing',
  path: '/financing',
  getParentRoute: () => rootRouteImport,
} as any)
const TestDriveRoute = TestDriveRouteImport.update({
  id: '/test-drive',
  path: '/test-drive',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryIndexRoute = InventoryIndexRouteImport.update({
  id: '/inventory/',
  path: '/inventory/',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryVehicleIdRoute = InventoryVehicleIdRouteImport.update({
  id: '/inventory/$vehicleId',
  path: '/inventory/$vehicleId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/car-finder': typeof CarFinderRoute
  '/financing': typeof FinancingRoute
  '/test-drive': typeof TestDriveRoute
  '/inventory/$vehicleId': typeof InventoryVehicleIdRoute
  '/inventory/': typeof InventoryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/car-finder': typeof CarFinderRoute
  '/financing': typeof FinancingRoute
  '/test-drive': typeof TestDriveRoute
  '/inventory/$vehicleId': typeof InventoryVehicleIdRoute
  '/inventory': typeof InventoryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/car-finder': typeof CarFinderRoute
  '/financing': typeof FinancingRoute
  '/test-drive': typeof TestDriveRoute
  '/inventory/$vehicleId': typeof InventoryVehicleIdRoute
  '/inventory/': typeof InventoryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/car-finder'
    | '/financing'
    | '/test-drive'
    | '/inventory/$vehicleId'
    | '/inventory/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/car-finder'
    | '/financing'
    | '/test-drive'
    | '/inventory/$vehicleId'
    | '/inventory'
  id:
    | '__root__'
    | '/'
    | '/car-finder'
    | '/financing'
    | '/test-drive'
    | '/inventory/$vehicleId'
    | '/inventory/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CarFinderRoute: typeof CarFinderRoute
  FinancingRoute: typeof FinancingRoute
  TestDriveRoute: typeof TestDriveRoute
  InventoryVehicleIdRoute: typeof InventoryVehicleIdRoute
  InventoryIndexRoute: typeof InventoryIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/car-finder': {
      id: '/car-finder'
      path: '/car-finder'
      fullPath: '/car-finder'
      preLoaderRoute: typeof CarFinderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financing': {
      id: '/financing'
      path: '/financing'
      fullPath: '/financing'
      preLoaderRoute: typeof FinancingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test-drive': {
      id: '/test-drive'
      path: '/test-drive'
      fullPath: '/test-drive'
      preLoaderRoute: typeof TestDriveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/': {
      id: '/inventory/'
      path: '/inventory'
      fullPath: '/inventory/'
      preLoaderRoute: typeof InventoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/$vehicleId': {
      id: '/inventory/$vehicleId'
      path: '/inventory/$vehicleId'
      fullPath: '/inventory/$vehicleId'
      preLoaderRoute: typeof InventoryVehicleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CarFinderRoute: CarFinderRoute,
  FinancingRoute: FinancingRoute,
  TestDriveRoute: TestDriveRoute,
  InventoryVehicleIdRoute: InventoryVehicleIdRoute,
  InventoryIndexRoute: InventoryIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
