/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CarFinderRouteImport } from './routes/car-finder'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FinancingRouteImport } from './routes/financing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TestDriveRouteImport } from './routes/test-drive'
import { Route as InventoryIndexRouteImport } from './routes/inventory.index'
import { Route as InventoryVehicleIdRouteImport } from './routes/inventory.$vehicleId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CarFinderRoute = CarFinderRouteImport.update({
  id: '/car-finder',
  path: '/car-finder',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FinancingRoute = FinancingRouteImport.update({
  id: '/financing',
  path: '/financing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TestDriveRoute = TestDriveRouteImport.update({
  id: '/test-drive',
  path: '/test-drive',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryIndexRoute = InventoryIndexRouteImport.update({
  id: '/inventory/',
  path: '/inventory/',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryVehicleIdRoute = InventoryVehicleIdRouteImport.update({
  id: '/inventory/$vehicleId',
  path: '/inventory/$vehicleId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/car-finder': typeof CarFinderRoute
  '/contact': typeof ContactRoute
  '/financing': typeof FinancingRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/test-drive': typeof TestDriveRoute
  '/inventory/$vehicleId': typeof InventoryVehicleIdRoute
  '/inventory/': typeof InventoryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/car-finder': typeof CarFinderRoute
  '/contact': typeof ContactRoute
  '/financing': typeof FinancingRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/test-drive': typeof TestDriveRoute
  '/inventory/$vehicleId': typeof InventoryVehicleIdRoute
  '/inventory': typeof InventoryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/car-finder': typeof CarFinderRoute
  '/contact': typeof ContactRoute
  '/financing': typeof FinancingRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/test-drive': typeof TestDriveRoute
  '/inventory/$vehicleId': typeof InventoryVehicleIdRoute
  '/inventory/': typeof InventoryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/car-finder'
    | '/contact'
    | '/financing'
    | '/privacy'
    | '/terms'
    | '/test-drive'
    | '/inventory/$vehicleId'
    | '/inventory/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/car-finder'
    | '/contact'
    | '/financing'
    | '/privacy'
    | '/terms'
    | '/test-drive'
    | '/inventory/$vehicleId'
    | '/inventory'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/car-finder'
    | '/contact'
    | '/financing'
    | '/privacy'
    | '/terms'
    | '/test-drive'
    | '/inventory/$vehicleId'
    | '/inventory/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  CarFinderRoute: typeof CarFinderRoute
  ContactRoute: typeof ContactRoute
  FinancingRoute: typeof FinancingRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  TestDriveRoute: typeof TestDriveRoute
  InventoryVehicleIdRoute: typeof InventoryVehicleIdRoute
  InventoryIndexRoute: typeof InventoryIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/car-finder': {
      id: '/car-finder'
      path: '/car-finder'
      fullPath: '/car-finder'
      preLoaderRoute: typeof CarFinderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financing': {
      id: '/financing'
      path: '/financing'
      fullPath: '/financing'
      preLoaderRoute: typeof FinancingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test-drive': {
      id: '/test-drive'
      path: '/test-drive'
      fullPath: '/test-drive'
      preLoaderRoute: typeof TestDriveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/': {
      id: '/inventory/'
      path: '/inventory'
      fullPath: '/inventory/'
      preLoaderRoute: typeof InventoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/$vehicleId': {
      id: '/inventory/$vehicleId'
      path: '/inventory/$vehicleId'
      fullPath: '/inventory/$vehicleId'
      preLoaderRoute: typeof InventoryVehicleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  CarFinderRoute: CarFinderRoute,
  ContactRoute: ContactRoute,
  FinancingRoute: FinancingRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  TestDriveRoute: TestDriveRoute,
  InventoryVehicleIdRoute: InventoryVehicleIdRoute,
  InventoryIndexRoute: InventoryIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
